name: manual

on:
  push:
    branches: [master]

  # to run this workflow manually from the Actio ns tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          
        run: git lfs fetch --all;git push --force https://chavhanrv111:$HF_TOKEN@huggingface.co/spaces/Sumit7864/Image-Enhancer
